# Generated by Django 5.0.6 on 2025-04-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('anomaly_score', models.FloatField()),
                ('suspicious_flag', models.IntegerField()),
                ('account_balance', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Quarantined', 'Quarantined'), ('Authorized', 'Authorized'), ('Flagged', 'Flagged')], default='Pending', max_length=20)),
            ],
        ),
    ]
