# Generated by Django 5.2.1 on 2025-05-11 07:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predictor", "0002_audittrail"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="fraud_probability",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_fraudulent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdraw", "Withdraw"),
                    ("transfer", "Transfer"),
                ],
                default=django.utils.timezone.now,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("balance", models.FloatField(default=0.0)),
                (
                    "parent_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_clients",
                        to="predictor.client",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="predictor.client",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_transfers",
                to="predictor.client",
            ),
        ),
    ]
