# Generated by Django 5.2.1 on 2025-05-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predictor", "0003_transaction_fraud_probability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdraw", "Withdraw"),
                    ("transfer", "Transfer"),
                ],
                default="deposit",
                max_length=10,
            ),
        ),
    ]
