# Generated by Django 5.2.1 on 2025-05-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predictor", "0004_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100)),
                ("fraud_probability", models.FloatField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
